sonar.projectKey=68bb4c361346849e1b99ae6d9f4d3b65134f3f3b
sonar.organization=ezeagusibarra001

sonar.sources=src

sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/__tests__/**

sonar.exclusions=\
dist/**,\
node_modules/**,\
coverage/**

sonar.javascript.lcov.reportPaths=coverage/unit/lcov.info

sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=typescript:S2068
sonar.issue.ignore.multicriteria.e1.resourceKey=**/helpers.ts